### ISSUE TITLE
Could you upload STEP or OBJ files

### ISSUE THREAD

**Issue by GitjoPowershell** [geoffrey-young/3D-Printing#2]
Hi,
First I would like to thank you for your design that i use since a while, however i recently moved to TAP on my voron V2 and I found the following issues on the TAP using sb-lgx-cw2-v5 
1: the front hole for the LGX screw miss some clearance (the screw head should enter into the hole)
2: the bottom part where the piece enter into the carriage miss a bit of clearance, i had to cut it with an exacto to make it fit

does it sounds possible that you upload the STEP or Obj files of your model to allow some tuning and make it compliant with TAP ?

Happy endings and once again thanks for your work !

**Comment by geoffrey-young** [comment]
hi :)

with respect to the lgx screw
clearance, m3 x 27 low profile screws are impossible to find, so the lack of recess actually allows us all to use standard m3x30 screws for mounting to the x carriage.  there
is plenty of room in the stealtburner housing for the screw heads, so we all get a little quality of life improvement :)

as for issue 2, I suspect that has more
to do with your overhang slicer settings -
I’ve printed it at least a dozen times and never had a fit issue. 

I use blender, so all I have to offer is stl files, unfortunately.  otherwise I’d happily offer up full cad. 

I’m really glad you found the models useful, and thanks for taking the time to point out potential issues - much appreciated!
